
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uekwoqakoyfwkgpkbuty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVla3dvcWFrb3lmd2tncGtidXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODE3OTUsImV4cCI6MjA2MTU1Nzc5NX0.2VU63DZcXDuBCEuvX9HNyiyIPCigmOGBgDoUDM1OeZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
